package:
  name: deeplabcut-desktop
  version: 0.0.2

source:
  path: .

build:
  number: 1
  skip: true  # [not linux]

requirements:
  run:
    - deeplabcut >=2.3.4
    # PySide6 is just too experimental at the moment
    - pyside2
    - napari-deeplabcut
    # Sigh, this will pull in all of pyqt5...
    # https://github.com/conda-forge/napari-feedstock/issues/47
    - napari

test:
  commands:
    - echo No valuable test. Requires desktop interaction.

about:
  home: https://github.com/ramonaoptics/deeplabcut-desktop-feedstock
  summary: Desktop launchers for DeepLabCut when installed in linux
  description: |
    This will create a desktop launcher for DeepLabCut. The launcher will override
    other installed DeepLabCut launchers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk

